// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDz4oSCAwKbnJFG3pcAKwU1C5oiMCDCods',
    appId: '1:906417198144:web:f5fa050f66b00e84d37ba5',
    messagingSenderId: '906417198144',
    projectId: 'suits-app-f4769',
    authDomain: 'suits-app-f4769.firebaseapp.com',
    storageBucket: 'suits-app-f4769.firebasestorage.app',
    measurementId: 'G-RVTF3Q8QXP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtcXIQuiNfHLiKUif4GKj4bNHyOUK9hSY',
    appId: '1:906417198144:android:a2a692fff4a93138d37ba5',
    messagingSenderId: '906417198144',
    projectId: 'suits-app-f4769',
    storageBucket: 'suits-app-f4769.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_oCjupYub6WuU_HdGrTCAUk65ZrJi4VY',
    appId: '1:906417198144:ios:15f4d3c87fcc18c7d37ba5',
    messagingSenderId: '906417198144',
    projectId: 'suits-app-f4769',
    storageBucket: 'suits-app-f4769.firebasestorage.app',
    iosBundleId: 'com.example.suitsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_oCjupYub6WuU_HdGrTCAUk65ZrJi4VY',
    appId: '1:906417198144:ios:15f4d3c87fcc18c7d37ba5',
    messagingSenderId: '906417198144',
    projectId: 'suits-app-f4769',
    storageBucket: 'suits-app-f4769.firebasestorage.app',
    iosBundleId: 'com.example.suitsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDz4oSCAwKbnJFG3pcAKwU1C5oiMCDCods',
    appId: '1:906417198144:web:93e4f083253fda29d37ba5',
    messagingSenderId: '906417198144',
    projectId: 'suits-app-f4769',
    authDomain: 'suits-app-f4769.firebaseapp.com',
    storageBucket: 'suits-app-f4769.firebasestorage.app',
    measurementId: 'G-E60Z320SD9',
  );
}
